[profile.default]
solc = "0.8.27"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=dependencies/forge-std-1.9.4/src/",
    "foundry-devops/=dependencies/foundry-devops-0.2.2/src/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
]
fs_permissions = [{ access = "read", path = "./broadcast" }]

[dependencies]
forge-std = { version = "1.9.4" }
foundry-devops = { version = "0.2.2" }
"@openzeppelin-contracts" = { version = "5.1.0" }
"@openzeppelin-contracts-upgradeable" = { version = "5.1.0" }

[soldeer]
remappings_generate = false
remappings_regenerate = false

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 128
fail_on_revert = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
